In [77]:
import pandas as pd
import numpy as np
import DBCV
from dtaidistance import dtw
from dtaidistance import ed
from btseg.clustering.hdbscan_clustering import HDBSCANClusterer
from itertools import product
from sklearn.metrics import silhouette_score

In [2]:
df = pd.read_csv('time_series_1.csv')
df.head()

,id,path,slice_path,a_0,a_1,a_2,a_3,a_4,a_5,a_6,...,a_350,a_351,a_352,a_353,a_354,a_355,a_356,a_357,a_358,a_359
0,1,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,109.041277,113.159180,113.282832,108.558740,106.794195,105.076163,103.406963,...,72.532751,102.420701,99.984999,99.724621,99.503769,100.319490,102.176318,104.076895,107.004673,107.004673
1,2,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,62.072538,64.195015,65.375837,66.483081,66.753277,67.082039,67.468511,...,66.490601,66.098411,61.660360,60.530984,60.299254,60.207973,60.074953,60.033324,60.000000,61.032778
2,3,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,91.049437,90.088845,89.202018,89.274856,88.459030,87.572827,87.692645,...,92.655275,92.541882,92.347171,92.265920,92.135769,92.086915,92.048900,92.005435,92.005435,92.021737
3,4,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,3.000000,3.000000,3.000000,3.000000,7.211103,7.211103,7.211103,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
4,5,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,C:/Users/Gilberto/Desktop/Gilberto/Projetos/bt...,39.115214,39.204592,39.319207,39.458839,39.623226,39.812058,40.024992,...,41.593269,41.593269,40.311289,40.199502,39.115214,39.051248,39.012818,39.000000,39.012818,39.051248

In [3]:
X = df.drop(['id', 'path', 'slice_path'], axis=1).values
len(X)

150

In [108]:
results_dict = {
    'noise': [],
    'p_noise': [],
    'instances': [],
    'p_instances': [],
    'smallest_group': [],
    'biggest_group': [],
    'average_size': [],
#     'q1': [],
#     'q2': [],
#     'q3': [],
    'silhouette_score': [],
    'mask': [],t
    'metric': [],
    'min_cluster_samples': [],
    'min_samples': [],
    'cluster_selection_method': []
}

In [106]:
def generate_dtw_matrix(X):
    X = np.array(X)
    distance_matrix = dtw.distance_matrix_fast(X)
    return distance_matrix

In [109]:
min_cluster_samples = [5, 10, 15, 20]
min_samples = [3, 4, 5]
metric = ['euclidean', 'dtw']
cluster_selection_method = ['leaf', 'eom']

for c in product(min_cluster_samples, metric, min_samples, cluster_selection_method):
    hdbscan = HDBSCANClusterer(
        min_cluster_samples=c[0],
        metric=c[1],
        min_samples=c[2],
        cluster_selection_method=c[3]
    )
    hdbscan.fit(X)
    out_labels = hdbscan.model.labels_
    counts = np.unique(out_labels, return_counts=True)
    
    results_dict['noise'].append(counts[1][0]) # Numero de instÃ¢ncias detectadas como ruido
    results_dict['p_noise'].append(counts[1][0] / counts[1].sum()) # Porcentagem de ruido
    results_dict['instances'].append(counts[1][1:].sum()) # Numero de instÃ¢ncias em algum grupo
    results_dict['p_instances'].append(counts[1][1:].sum() / counts[1].sum()) # Porcentagem de instancias agrupadas

    results_dict['smallest_group'].append(counts[1][0] if len(counts[1]) == 1 else counts[1][1:].min())
    results_dict['biggest_group'].append(counts[1][0] if len(counts[1]) == 1 else counts[1][1:].max())
    results_dict['average_size'].append(counts[1][0] if len(counts[1]) == 1 else counts[1][1:].mean())
    
    Xn = df.drop(['id', 'path', 'slice_path'], axis=1).copy()
    Xn['label'] = out_labels
    Xn = Xn.query('label != -1')

    if c[1] == 'euclidean':
        if len(Xn) == 0:
            score = 0
        else:
            score = silhouette_score(Xn.drop(['label'], axis=1), Xn['label'])
    elif c[1] == 'dtw':
        if len(Xn) == 0:
            score = 0
        else:
            inputs = Xn.drop(['label'], axis=1).values
            labels = Xn['label']
            score = silhouette_score(generate_dtw_matrix(inputs), labels, metric='precomputed')
    else:
        score = 0

    results_dict['silhouette_score'].append(score)
#     results_dict['q1'].append(None)
#     results_dict['q2'].append(None)
#     results_dict['q3'].append(None)
    results_dict['mask'].append(1)
    results_dict['metric'].append(c[1])
    results_dict['min_cluster_samples'].append(c[0])
    results_dict['min_samples'].append(c[2])
    results_dict['cluster_selection_method'].append(c[3])

In [110]:
results_df = pd.DataFrame(results_dict)
results_df

,noise,p_noise,instances,p_instances,smallest_group,biggest_group,average_size,silhouette_score,mask,metric,min_cluster_samples,min_samples,cluster_selection_method
0,96,0.640000,54,0.360000,15,23,18.000000,0.492334,1,euclidean,5,3,leaf
1,96,0.640000,54,0.360000,15,23,18.000000,0.492334,1,euclidean,5,3,eom
2,106,0.706667,44,0.293333,10,20,14.666667,0.553571,1,euclidean,5,4,leaf
3,106,0.706667,44,0.293333,10,20,14.666667,0.553571,1,euclidean,5,4,eom
4,116,0.773333,34,0.226667,6,18,11.333333,0.601495,1,euclidean,5,5,leaf
5,116,0.773333,34,0.226667,6,18,11.333333,0.601495,1,euclidean,5,5,eom
6,81,0.540000,69,0.460000,14,38,23.000000,0.570573,1,dtw,5,3,leaf
7,81,0.540000,69,0.460000,14,38,23.000000,0.570573,1,dtw,5,3,eom
8,78,0.520000,72,0.480000,14,44,24.000000,0.517765,1,dtw,5,4,leaf
9,78,0.520000,72,0.480000,14,44,24.000000,0.517765,1,dtw,5,4,eom
10,88,0.586667,62,0.413333,9,39,20.666667,0.561935,1,dtw,5,5,leaf
11,88,0.586667,62,0.413333,9,39,20.666667,0.561935,1,dtw,5,5,eom
12,96,0.640000,54,0.360000,15,23,18.000000,0.492334,1,euclidean,10,3,leaf
13,68,0.453333,82,0.546667,16,66,41.000000,0.408315,1,euclidean,10,3,eom
14,106,0.706667,44,0.293333,10,20,14.666667,0.553571,1,euclidean,10,4,leaf
15,77,0.513333,73,0.486667,10,63,36.500000,0.443952,1,euclidean,10,4,eom
16,122,0.813333,28,0.186667,10,18,14.000000,0.596101,1,euclidean,10,5,leaf
17,122,0.813333,28,0.186667,10,18,14.000000,0.596101,1,euclidean,10,5,eom
18,81,0.540000,69,0.460000,14,38,23.000000,0.570573,1,dtw,10,3,leaf
19,81,0.540000,69,0.460000,14,38,23.000000,0.570573,1,dtw,10,3,eom
20,78,0.520000,72,0.480000,14,44,24.000000,0.517765,1,dtw,10,4,leaf
21,78,0.520000,72,0.480000,14,44,24.000000,0.517765,1,dtw,10,4,eom
22,62,0.413333,88,0.586667,14,74,44.000000,0.589080,1,dtw,10,5,leaf
23,62,0.413333,88,0.586667,14,74,44.000000,0.589080,1,dtw,10,5,eom
24,96,0.640000,54,0.360000,15,23,18.000000,0.492334,1,euclidean,15,3,leaf
25,68,0.453333,82,0.546667,16,66,41.000000,0.408315,1,euclidean,15,3,eom
26,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,15,4,leaf
27,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,15,4,eom
28,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,15,5,leaf
29,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,15,5,eom
30,72,0.480000,78,0.520000,17,61,39.000000,0.417033,1,dtw,15,3,leaf
31,72,0.480000,78,0.520000,17,61,39.000000,0.417033,1,dtw,15,3,eom
32,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,15,4,leaf
33,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,15,4,eom
34,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,15,5,leaf
35,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,15,5,eom
36,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,20,3,leaf
37,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,20,3,eom
38,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,20,4,leaf
39,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,20,4,eom
40,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,20,5,leaf
41,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,euclidean,20,5,eom
42,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,20,3,leaf
43,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,20,3,eom
44,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,20,4,leaf
45,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,20,4,eom
46,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,20,5,leaf
47,150,1.000000,0,0.000000,150,150,150.000000,0.000000,1,dtw,20,5,eom